<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilos/Tema10_xml.css"?>
<!DOCTYPE empresa[
    <!ELEMENT empresa (trabajador+)>
    <!ELEMENT trabajador (departamento,nombre,apellidos,cargo+,movil+,fijo?)>
    <!ELEMENT departamento (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT cargo (#PCDATA)>
    <!ELEMENT movil (#PCDATA)>
    <!ELEMENT fijo (#PCDATA)>
    <!ATTLIST trabajador
        genero (femenino|masculino) #REQUIRED
        id CDATA #IMPLIED>
]>

<empresa>
    <trabajador genero="masculino" id="123">
        <departamento>Informática</departamento>
        <nombre>Juan</nombre>
        <apellidos>Martínez Pérez</apellidos>
        <cargo>Coordinados</cargo>
        <movil>123123123</movil>
    </trabajador>
    <trabajador genero="femenino">
        <departamento>Marketing</departamento>
        <nombre>Tomasa</nombre>
        <apellidos>Martínez Pérez</apellidos>
        <cargo>Técnico</cargo>
        <movil>123123123</movil>
        <fijo>123123123</fijo>
    </trabajador>
</empresa>